# Generated by Django 5.2.6 on 2025-10-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0004_pendingloginlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
