# Generated by Django 5.2.6 on 2025-10-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
    ]
