# Generated by Django 5.2.6 on 2025-10-28 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsAPI', '0001_initial'),
        ('orderAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orderAPI.order'),
        ),
    ]
