# Generated by Django 5.2.6 on 2025-10-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=models.SET_NULL, related_name='products', to='categoryAPI.category'),
        ),
    ]
