# Generated by Django 5.2.6 on 2025-10-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryAPI', '0002_alter_category_options_category_parent'),
        ('productAPI', '0002_remove_product_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categoryAPI.category'),
            preserve_default=False,
        ),
    ]
