# Generated by Django 5.2.6 on 2025-10-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0004_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
