# Generated by Django 5.2.6 on 2025-10-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0005_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
