# Generated by Django 5.2.6 on 2025-10-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0006_remove_product_description'),
    ]

    operations = [
    ]
