# Generated by Django 5.2.6 on 2025-10-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0007_auto_20251013_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('dry_food', 'Dry Food'),
                    ('wet_food', 'Wet Food'),
                    ('pet_care', 'Pet Care'),
                    ('pet_treats', 'Pet Treats'),
                    ('pet_milk', 'Pet Milk'),
                    ('cat_litter', 'Cat Litter'),
                    ('other_essentials', 'Other Essentials'),
                    ('merch', 'Merch'),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
