# Generated by Django 5.2.6 on 2025-10-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
