# Generated by Django 5.2.6 on 2025-10-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPI', '0002_inventory_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
