# Generated by Django 5.2.6 on 2025-10-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPI', '0004_alter_inventory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products/variants/'),
        ),
    ]
