# Generated by Django 5.2.6 on 2025-10-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPI', '0005_alter_inventory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
