# Generated by Django 5.2.6 on 2025-10-18 19:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPI', '0006_inventory_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
