# Generated by Django 5.2.6 on 2025-10-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPI', '0007_alter_inventory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='image_url',
        ),
    ]
