# Generated by Django 5.2.6 on 2025-10-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentAPI', '0002_payment_proof_image_alter_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('delivery', 'Delivery')], default='pending', max_length=20),
        ),
    ]
