# Generated by Django 5.2.6 on 2025-10-18 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderAPI', '0001_initial'),
        ('paymentAPI', '0003_remove_payment_transaction_id_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orderAPI.order'),
        ),
    ]
