# Generated by Django 5.2.6 on 2025-10-27 11:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentAPI', '0004_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('gcash', 'GCash'), ('stripe', 'Stripe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
